name: Create Release Tag for kustomize

on:
  issues:
    types:
      [opened, labeled, edited] # Runs at 8 AM and 8 PM daily

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Git with user info
      env:
          GITHUB_TOKEN: ${{ secrets.GH_SYSTEMSDT_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_SYSTEMSDT_TOKEN }}
          GIT_CONFIG_NAME: ${{ env.GH_SYSTEMSDT_USERNAME }}
          GIT_CONFIG_EMAIL: ${{ secrets.GH_SYSTEMSDT_EMAIL }}
      run: |
        echo "----------------------------"
        echo $GIT_CONFIG_EMAIL
        echo "----------------------------"
        echo $GIT_CONFIG_NAME
        echo "----------------------------"
        git config user.email $GIT_CONFIG_EMAIL
        git config user.name $GIT_CONFIG_NAME
        

    - name: Create Release Tag
      env:
          GITHUB_TOKEN: ${{ secrets.GH_SYSTEMSDT_TOKEN }}
      run: |
        echo "----------------------------"
        echo $GH_SYSTEMSDT_TOKEN
        echo "----------------------------"
